### ISSUE TITLE
Error building cartographer: Unknown CMAKE_BUILD_TYPE: None

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosdistro-testing#3]
I'm not sure what to do about this one. Looks like a build type of None is standard on the ROS 1 farm too.

@wjwwood any ideas?

```
15:57:35 CMake Error at cmake/functions.cmake:108 (message):
15:57:35   Unknown CMAKE_BUILD_TYPE: None
15:57:35 Call Stack (most recent call first):
15:57:35   CMakeLists.txt:26 (google_initialize_cartographer_project)
15:57:35 
15:57:35 
15:57:35 -- Configuring incomplete, errors occurred!
```

**Comment by wjwwood** [comment]
Perhaps it is being set to `None`, but it needs to be unset for cartographer's code to default it to release:

https://github.com/ros2/cartographer/blob/ros2/cmake/functions.cmake#L88-L90

So, maybe a work around is to patch the rules file for cartographer to explicitly set the build type to Release, since that's what they want anyways.

This happens in ROS 1 from time to time as well:

http://wiki.ros.org/bloom/Tutorials/ChangeBuildFlags

**Comment by nuclearsandwich** [comment]
Resolved by https://github.com/nuclearsandwich/cartographer-release/commit/9dd7d5072aae210620060c816899dc9c4e089424

**Comment by dirk-thomas** [comment]
By patching it only in the release file rather than in the source repo the same problem will still happen for users building from source.

**Comment by clalancette** [comment]
I don't think that will happen.  At least, cartographer builds just fine on my local machines, as well as on the build farm.  I can't say I totally understand why the debian package is having a problem, but I think it is restricted to that.

**Comment by nuclearsandwich** [comment]
> By patching it only in the release file rather than in the source repo the same problem will still happen for users building from source.

What mechanism in the source repository exists that would override the `-DCMAKE_BUILD_TYPE=None` that is set by debhelper? This is needed because debhelper explicitly sets None as the build type rather than leaving it defaulted to None and allowing source to decide on its own default.
